[package]
name = "skeptic-readme"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
build = "build.rs"

[build-dependencies.skeptic]
path = "src/skeptic"

# This makes the tests that link to skeptic in README.md work
[dependencies.skeptic]
path = "src/skeptic"
