[package]
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "Test your Rust markdown documentation via Cargo"
license = "MIT/Apache-2.0"
name = "skeptic"
repository = "https://github.com/brson/rust-skeptic"
version = "0.10.1"

[dependencies]
pulldown-cmark = "0.0.15"
tempdir = "0.3.5"
walkdir = "1.0"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
toml = "0.4.2"

[dependencies.error-chain]
version = "0.10.0"
default-features = false

[lib]
name = "skeptic"
path = "lib.rs"
