[package]
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "Test your Rust markdown documentation via Cargo"
license = "MIT/Apache-2.0"
name = "skeptic"
repository = "https://github.com/brson/rust-skeptic"
version = "0.10.0"

[dependencies]
pulldown-cmark = "0.0.14"
tempdir = "0.3.5"

[lib]
name = "skeptic"
path = "lib.rs"
